"""Generates DATA_DICTIONARY.md by introspecting every *.schema.json file.

Run this whenever a schema changes:
    python3 generate_data_dictionary.py

The output can never silently drift from the real schemas the way a
hand-authored data dictionary would, because it IS the schemas, flattened.
"""

import glob
import json
import os

SCHEMA_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_PATH = os.path.join(SCHEMA_DIR, "DATA_DICTIONARY.md")


def type_label(subschema: dict) -> str:
    # Use "/" not "|" to join union types -- "|" is the markdown table
    # column delimiter and would otherwise silently split this cell.
    t = subschema.get("type", "")
    if isinstance(t, list):
        return "/".join(t)
    return t or ""


def flatten(subschema: dict, path: str, source_file: str, rows: list):
    props = subschema.get("properties")
    if not props:
        return
    for key, field_schema in props.items():
        field_path = f"{path}.{key}" if path else key
        enum = field_schema.get("enum")
        enum_label = ", ".join(str(v) for v in enum if v is not None) if enum else ""
        rows.append({
            "field": field_path,
            "type": type_label(field_schema),
            "enum": enum_label,
            "description": (field_schema.get("description") or "").replace("\n", " "),
            "source": source_file,
        })
        field_type = field_schema.get("type")
        is_object = field_type == "object" or (isinstance(field_type, list) and "object" in field_type)
        if is_object and "properties" in field_schema:
            flatten(field_schema, field_path, source_file, rows)
        elif field_type == "array":
            items = field_schema.get("items")
            if isinstance(items, dict) and "properties" in items:
                flatten(items, field_path + "[]", source_file, rows)


def generate() -> list:
    rows = []
    schema_files = sorted(glob.glob(os.path.join(SCHEMA_DIR, "*.schema.json")))
    for path in schema_files:
        source_file = os.path.basename(path)
        with open(path) as f:
            schema = json.load(f)
        flatten(schema, "", source_file, rows)
    return rows


def render_markdown(rows: list) -> str:
    lines = [
        "# Project Atlas — Data Dictionary",
        "",
        f"Auto-generated by `generate_data_dictionary.py` from every `*.schema.json` in this directory. "
        f"Do not hand-edit — re-run the generator after any schema change. {len(rows)} fields across "
        f"{len({r['source'] for r in rows})} schemas.",
        "",
        "| Field | Type | Enum values | Description | Source schema |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        description = r["description"].replace("|", "\\|")
        enum = r["enum"].replace("|", "\\|")
        lines.append(f"| `{r['field']}` | {r['type']} | {enum} | {description} | `{r['source']}` |")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    rows = generate()
    markdown = render_markdown(rows)
    with open(OUTPUT_PATH, "w") as f:
        f.write(markdown)
    print(f"Wrote {len(rows)} fields from {len({r['source'] for r in rows})} schemas to {OUTPUT_PATH}")
